version: '3.9'

# services represents our containers
services:
  # mongodb service
  mongo_db:
    container_name: db_container
  # mongo_db and container_name is user defined name
    image: ${DATABASENAME}:latest
    restart: always
    # conatiner will be restart in any failure
    volumes: 
      - mongo_db:/data/db
    # if we restart our conatiner data will be not 
    # there so for this purpose we will define a volumes
    # file of databae will be mapped on our local machine
    # mongo_db is the volume
    # /data/db is fixed keyword for mongodb
    ports:
      - "27017:27017"


  # node apis service
  node_api:
  # now here we will use node image from dockerfile by build command a
    #and dot represents dockerfile path is in current directory 
    build: .
    ports:
      - ${PORT_CONTAINER}:4000
      # 4000 port on our local machine will be mapped to port 3005 in container
    volumes:
     - ./:/usr/src/app  
    environment: 
      PORT: 3000
      MONGO_URL: mongodb://mongo_db:27017
#  mongodb://localhost:27017 , but we write service name or container name
# instead of localhost bcoz container is runnning in nod eimage

      DB_NAME: nodeDatabase
      NAME: Harjot Singh  

    external_links:
      - mongo_db  

      # now we will pass one more flag so that node xontainer will only run 
      # when only mongo service is avaialable
    depends_on:
      - mongo_db  

# we are creating a service name mongo_db that is manage by container ,so

# we want to persist our data even if we shut down our container      # 
# so use this
volumes:
  mongo_db: {}  #curly braces are optional,which means currently empty,also we can use simply write - mongo_db