version: "3"

services:
  app:
        container_name: NodeApp
        restart: always
        build: .
        ports:
          - "3000:6000"
        links: 
          - mongo_d

  mongo_d:
        container_name: mongo_con
        image: mongo
        ports:
          - "27017:27017"        
