# getting base image ubuntu
FROM ubuntu

#Optional maintainer 
#MAINTAINER harjot singh <email>

# ["echo","checking appending with entrypoint"]

#ENTRYPOINT ["ls","-l"]

#CMD ["echo","checking appending with cmd command"]
# ["ls","-l"]

RUN apt-get update
#run gets executing during building of an image

CMD ["echo","Hello World from first dcoker image"]
#cmd is executed when u make container out of the image

